version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: notesDB
      POSTGRES_USER: serverNoteS
      POSTGRES_PASSWORD: notes123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notesDB
      SPRING_DATASOURCE_USERNAME: serverNoteS
      SPRING_DATASOURCE_PASSWORD: notes123

volumes:
  db_data: